import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Basic;

/**
 * Tb_Customer ORM class.
 * Generated by IntelliJ Idea.
 *
 * @author Konrad Szwedo
 * @version 0.7L
 */
@Entity
@Table(name = "Tb_Customer")
public class TbCustomerEntity {
    private int id;
    private String firstName;
    private String lastName;

    /**
     * Getter for customer ID.
     *
     * @return int customer ID.
     */
    @Id
    @Column(name = "Id")
    public int getId() {
        return id;
    }

    /**
     * Setter for customer ID.
     *
     * @param id customer ID
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Getter for customer first name.
     *
     * @return customer first name
     */
    @Basic
    @Column(name = "firstName")
    public String getFirstName() {
        return firstName;
    }

    /**
     * Setter for customer first name.
     *
     * @param firstName customer first name
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * Getter for customer last name.
     *
     * @return String customer last name
     */
    @Basic
    @Column(name = "lastName")
    public String getLastName() {
        return lastName;
    }

    /**
     * Setter for customer last name.
     *
     * @param lastName Customer last name.
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * @param o second object to compare
     * @return true if equals, otherwise false
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        TbCustomerEntity that = (TbCustomerEntity) o;

        return id == that.id && (firstName != null ? firstName
                .equals(that.firstName) : that.firstName == null &&
                (lastName != null ? lastName.equals(that.lastName)
                        : that.lastName == null));

    }

    /**
     * Hashcode of object.
     *
     * @return object hashcode.
     */
    @Override
    public int hashCode() {
        int result = id;
        result = 31 * result + (firstName != null ? firstName.hashCode() : 0);
        result = 31 * result + (lastName != null ? lastName.hashCode() : 0);
        return result;
    }
}
