//import javax.persistence.;

import javax.persistence.*;
import java.sql.Timestamp;

/**
 * Created by Konrad on 07.05.2016.
 * AutoGenerated by IntelliJ
 */
@Entity
@Table(name = "TB_Insurance", schema = "dbo", catalog = "ZTP_zad7")
public class TbInsuranceEntity {
    private int id;
    private int customerId;
    private int modelId;
    private Timestamp dateFrom;
    private Timestamp dateTo;

    @Id
    @Column(name = "Id")
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Basic
    @Column(name = "customerId")
    public int getCustomerId() {
        return customerId;
    }

    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }

    @Basic
    @Column(name = "modelId")
    public int getModelId() {
        return modelId;
    }

    public void setModelId(int modelId) {
        this.modelId = modelId;
    }

    @Basic
    @Column(name = "dateFrom")
    public Timestamp getDateFrom() {
        return dateFrom;
    }

    public void setDateFrom(Timestamp dateFrom) {
        this.dateFrom = dateFrom;
    }

    @Basic
    @Column(name = "dateTo")
    public Timestamp getDateTo() {
        return dateTo;
    }

    public void setDateTo(Timestamp dateTo) {
        this.dateTo = dateTo;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        TbInsuranceEntity that = (TbInsuranceEntity) o;

        if (id != that.id) return false;
        if (customerId != that.customerId) return false;
        if (modelId != that.modelId) return false;
        if (dateFrom != null ? !dateFrom.equals(that.dateFrom) : that.dateFrom != null)
            return false;
        if (dateTo != null ? !dateTo.equals(that.dateTo) : that.dateTo != null)
            return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = id;
        result = 31 * result + customerId;
        result = 31 * result + modelId;
        result = 31 * result + (dateFrom != null ? dateFrom.hashCode() : 0);
        result = 31 * result + (dateTo != null ? dateTo.hashCode() : 0);
        return result;
    }
}
