import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Basic;

/**
 * Tb_Customer ORM class.
 * Generated by IntelliJ Idea.
 *
 * @author Konrad Szwedo
 * @version 0.7L
 */
@Entity
@Table(name = "Tb_Model")
public class TbModelEntity {
    private int id;
    private String model;

    /**
     * Getter for car ID
     *
     * @return int car ID
     */
    @Id
    @Column(name = "Id")
    public int getId() {
        return id;
    }

    /**
     * Setter for car ID.
     *
     * @param id int car ID.
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Getter for model field.
     *
     * @return String car model of current object.
     */
    @Basic
    @Column(name = "model")
    public String getModel() {
        return model;
    }


    /**
     * Setter for model field.
     *
     * @param model car model
     */
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * @param o second object to compare
     * @return true if equals, otherwise false
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        TbModelEntity that = (TbModelEntity) o;

        return id == that.id &&
                (model != null ? model.equals(that.model) : that.model == null);

    }

    /**
     * Hashcode of object.
     *
     * @return object hashcode.
     */
    @Override
    public int hashCode() {
        int result = id;
        result = 31 * result + (model != null ? model.hashCode() : 0);
        return result;
    }
}
